spring:
  data:
    mongodb:
      auto-index-creation: 'true'
      uri: ENC(t6FsTOCOpbXByGRbbRCrrqiSgBlLHlFSMG6hTP4eq0RKMZOujQU3GYukIWw3kpPT9bvY3bcyHYnIl/WxzL2YViHjM1Cc4Mf9qcM8mAnmdPDsNiRX6r6KW3R6bGeKRb3KBA0FXp6T1L6b525Z51yT9lp1GvJBKEvruzIBYHm7cPY=)
jwt:
  tokenExpiresAfterDays: '14'
  tokenPrefix: 'Bearer '
  secret: ENC(0MLm546s6aagsEGguJL5THMvdj9nCP0chF/W86GznaRBPVdTqcHzMG3KX0Ce/PT7nniZTk3RJPnCYjayv7ayc7ZeFMFJzb/LNv80DT6XRZ4=)
server:
  error:
    whitelabel:
      enabled: 'false'
